### ISSUE TITLE
Unnecessary trait bound in `format()`

### ISSUE THREAD

**Issue by austinglaser** [NerdyPepper/lotus#3]
I notice that your format method's signature is `pub fn format<T: Into<f64> + Display>(&self, in_number: T) -> String`. It seems to me that `in_number` does not need to be `Display`, since you immediately convert it to `f64` before doing anything with it

**Comment by oppiliappan** [comment]
You are right! Looks like some cruft code escaped my refactors. Ill fix this as soon as I get some time!
